2025-01-24 14:43:43,574 - app - DEBUG - Attempting pyodbc.connect...
2025-01-24 14:43:43,689 - app - DEBUG - Connection successful
2025-01-24 14:43:43,772 - app - ERROR - Error fetching workflow runs: ('42S22', "[42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'workflow_id'. (207) (SQLExecDirectW); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'time_to_red_signal'. (207); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'commit_message'. (207); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'pr_number'. (207); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Statement(s) could not be prepared. (8180)")
Traceback (most recent call last):
  File "C:\Users\akbansal\Downloads\github-dashboard\backend\app.py", line 294, in get_workflowruns
    cursor.execute(query, params)
pyodbc.ProgrammingError: ('42S22', "[42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'workflow_id'. (207) (SQLExecDirectW); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'time_to_red_signal'. (207); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'commit_message'. (207); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'pr_number'. (207); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Statement(s) could not be prepared. (8180)")
2025-01-24 14:43:43,974 - app - DEBUG - Connection closed successfully
2025-01-24 14:46:05,972 - app - INFO - Environment variables check:
2025-01-24 14:46:05,977 - app - INFO - DB_PASSWORD set: False
2025-01-24 14:46:05,977 - app - INFO - Starting Flask application...
2025-01-24 14:46:07,358 - app - INFO - Initial database connection test successful
